"use client";

import React, { useState, useEffect } from 'react';
import { HardDrive, ShieldCheck, RefreshCw, Loader2, Table, Search, AlertCircle, Database, CheckCircle2, Lock } from 'lucide-react';

export default function SandboxPage() {
  const [selectedTable, setSelectedTable] = useState<string>('customers');
  const [records, setRecords] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const fetchSandboxRecords = async (table: string) => {
    setIsLoading(true);
    setErrorMsg(null);
    setSelectedTable(table);
    try {
      const res = await fetch(`http://127.0.0.1:8000/api/pipeline/destination-records?table=${table}&limit=30`);
      if (res.ok) {
        const data = await res.json();
        if (data.status === 'success') {
          setRecords(data.records || []);
        } else {
          setErrorMsg(data.message || 'Failed to fetch destination records.');
          setRecords([]);
        }
      } else {
        setErrorMsg('Network error while connecting to sandbox endpoint.');
        setRecords([]);
      }
    } catch (err) {
      console.error('Sandbox fetch error:', err);
      setErrorMsg('Unable to connect to backend server.');
      setRecords([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchSandboxRecords('customers');
  }, []);

  const filteredRecords = records.filter((row) => {
    if (!searchTerm.trim()) return true;
    const term = searchTerm.toLowerCase();
    return Object.values(row).some((val) => String(val ?? '').toLowerCase().includes(term));
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Page Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-emerald-500/10 text-emerald-400 rounded-xl flex items-center justify-center border border-emerald-500/20 shadow-md">
            <HardDrive className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              Sandbox Environment
              <span className="text-xs font-mono px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                DESTINATION DB: neondb_anonymized
              </span>
            </h1>
            <p className="text-xs text-slate-400 mt-1">
              Isolated target database containing privacy-preserved records generated by Pipeline Step 12 & Step 13.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => fetchSandboxRecords(selectedTable)}
          className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold rounded-lg transition-colors flex items-center gap-2 border border-slate-700 shadow"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin text-emerald-400' : ''}`} />
          Refresh Sandbox
        </button>
      </div>

      {/* Metadata KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex items-center gap-3">
          <div className="p-2.5 bg-blue-500/10 text-blue-400 rounded-lg">
            <Database className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 uppercase font-semibold block">Target Database</span>
            <span className="text-xs font-mono font-bold text-emerald-400">neondb_anonymized</span>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex items-center gap-3">
          <div className="p-2.5 bg-purple-500/10 text-purple-400 rounded-lg">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 uppercase font-semibold block">Privacy Engine</span>
            <span className="text-xs font-bold text-white">Step 12 & 13 Active</span>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex items-center gap-3">
          <div className="p-2.5 bg-emerald-500/10 text-emerald-400 rounded-lg">
            <Lock className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 uppercase font-semibold block">Security Status</span>
            <span className="text-xs font-bold text-emerald-400">PII Masked & Tokenized</span>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex items-center gap-3">
          <div className="p-2.5 bg-amber-500/10 text-amber-400 rounded-lg">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 uppercase font-semibold block">Loaded Records</span>
            <span className="text-xs font-mono font-bold text-white">{records.length} Rows Rendered</span>
          </div>
        </div>
      </div>

      {/* Main Sandbox Data Workspace */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-6 shadow-xl">
        {/* Controls Header: Table Tabs & Search */}
        <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800">
          {/* Table Selector Tabs */}
          <div className="flex items-center gap-2">
            {['customers', 'employees', 'transactions', 'accounts'].map((tbl) => (
              <button
                key={tbl}
                type="button"
                onClick={() => fetchSandboxRecords(tbl)}
                className={`px-4 py-2 text-xs font-mono font-bold rounded-lg transition-all capitalize border flex items-center gap-2 ${
                  selectedTable === tbl
                    ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/50 shadow-md'
                    : 'bg-slate-950 text-slate-400 border-slate-800 hover:text-white hover:bg-slate-800'
                }`}
              >
                <Table className="w-3.5 h-3.5" />
                {tbl}
              </button>
            ))}
          </div>

          {/* Search Bar */}
          <div className="relative min-w-[240px]">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="Search anonymized rows..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-1.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 font-mono"
            />
          </div>
        </div>

        {/* Content Area */}
        {isLoading ? (
          <div className="py-20 text-center space-y-3">
            <Loader2 className="w-8 h-8 text-emerald-400 animate-spin mx-auto" />
            <p className="text-xs text-slate-400 font-mono">Fetching live records from destination database...</p>
          </div>
        ) : errorMsg ? (
          <div className="py-16 text-center space-y-3 bg-red-500/10 rounded-lg border border-red-500/30">
            <AlertCircle className="w-8 h-8 text-red-400 mx-auto" />
            <p className="text-xs text-red-300 font-medium">{errorMsg}</p>
            <button
              type="button"
              onClick={() => fetchSandboxRecords(selectedTable)}
              className="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold rounded-lg inline-flex items-center gap-2 border border-slate-700"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              Retry Fetching
            </button>
          </div>
        ) : filteredRecords.length > 0 ? (
          <div className="overflow-x-auto rounded-lg border border-slate-800">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-slate-950 text-slate-400 uppercase text-[10px] border-b border-slate-800">
                <tr>
                  {Object.keys(filteredRecords[0]).map((col) => (
                    <th key={col} className="px-4 py-3 font-semibold text-slate-300">
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 bg-slate-900/60">
                {filteredRecords.map((row, rIdx) => (
                  <tr key={rIdx} className="hover:bg-slate-800/40 transition-colors">
                    {Object.entries(row).map(([k, val]: [string, any]) => {
                      const valStr = String(val ?? '');
                      const isMasked = valStr.includes('*') || valStr.includes('xxxx');
                      const isHash = valStr.length > 20 && !valStr.includes('@') && !valStr.includes(' ');
                      return (
                        <td key={k} className="px-4 py-2.5 text-slate-200 whitespace-nowrap">
                          {isMasked ? (
                            <span className="bg-amber-500/20 text-amber-300 px-2 py-0.5 rounded border border-amber-500/30 text-[11px] font-bold">
                              {valStr}
                            </span>
                          ) : isHash ? (
                            <span className="bg-purple-500/20 text-purple-300 px-2 py-0.5 rounded border border-purple-500/30 text-[10px] font-bold truncate max-w-[150px] inline-block">
                              {valStr}
                            </span>
                          ) : (
                            valStr
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="py-16 text-center space-y-3 bg-slate-950/50 rounded-lg border border-slate-800">
            <AlertCircle className="w-8 h-8 text-amber-400 mx-auto" />
            <p className="text-xs text-slate-300">
              No anonymized records found in table <strong className="text-emerald-400 font-mono">{selectedTable}</strong>.
            </p>
            <p className="text-[11px] text-slate-500">
              Run the 17-step pipeline on <strong className="text-blue-400">/pipeline</strong> to populate anonymized records into <code className="text-emerald-400 font-mono">neondb_anonymized</code>.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
